name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
          python-version: '3.9'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker *.c*
      
    - name: run
      run: ./testchecker

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    - name: create coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage_sender
        path: ./*.html
        retention-days: 21
    
    - name: Receiver - Run and collect coverage
      run: |
          python sender_receiver.test.py
          coverage run --branch receiver.test.py
          coverage html
          coverage report
    - name: Upload Receiver test coverage
      uses: actions/upload-artifact@v2
      with:
          name: coverage_receiver
          path: ./htmlcov
          retention-days: 21    
    - name: Sender | Receiver
      run: |
          gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary | python sender_receiver.test.py | python receiver.test.py
